// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aJALrl6z8vguFObf4Q-M7M2QFS_wMkI',
    appId: '1:680639596708:web:b80e4b43b35bfef5cf3e31',
    messagingSenderId: '680639596708',
    projectId: 'favwidget',
    authDomain: 'favwidget.firebaseapp.com',
    storageBucket: 'favwidget.appspot.com',
    measurementId: 'G-ELBYJWT63S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwytP3Il7gK9epEc0dgdp67gWVk8NZV48',
    appId: '1:680639596708:android:5cf7fac7500b65d3cf3e31',
    messagingSenderId: '680639596708',
    projectId: 'favwidget',
    storageBucket: 'favwidget.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6OQyJKd3h5MWHxSS4pLJOEGFPBQ2i3k',
    appId: '1:680639596708:ios:c0e5ee1299f3164ecf3e31',
    messagingSenderId: '680639596708',
    projectId: 'favwidget',
    storageBucket: 'favwidget.appspot.com',
    iosClientId: '680639596708-umr2qhrm9lcc5lvg38bnqljl3d9mcika.apps.googleusercontent.com',
    iosBundleId: 'com.example.forge2dPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6OQyJKd3h5MWHxSS4pLJOEGFPBQ2i3k',
    appId: '1:680639596708:ios:c0e5ee1299f3164ecf3e31',
    messagingSenderId: '680639596708',
    projectId: 'favwidget',
    storageBucket: 'favwidget.appspot.com',
    iosClientId: '680639596708-umr2qhrm9lcc5lvg38bnqljl3d9mcika.apps.googleusercontent.com',
    iosBundleId: 'com.example.forge2dPicker',
  );
}
